### ISSUE TITLE
Add OEL7 Support

### ISSUE THREAD

**Issue by rangerzzoxz** [OraOpenSource/oraclexe-apex#10]
Add support for OEL7

**Comment by rangerzzoxz** [comment]
I can verify the same "build" process works on OEL7, although "yum install git -y" comes back as "already installed".

**Comment by martindsouza** [comment]
I think that's ok, as it's not returning an error. Can you please update the Supported OS's section in the main Readme and close the ticket? Thanks.

**Comment by rangerzzoxz** [comment]
Readme.md revised accordingly
