### ISSUE TITLE
Add rlwrap support

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oraclexe-apex#26]
See: https://bjornnaessens.wordpress.com/2012/08/14/installing-rlwrap-on-linux-saves-you-time/ for installation instructions

Demo on how to use it: http://www.talkapex.com/2013/03/oracle-instant-client-on-mac-os-x.html

Should include the .tar.gz file directly in project to guarantee location. I tried the git clone (for https://github.com/hanslub42/rlwrap) option however the `configure` file needs to be built and not really worth the extra installs.

**Comment by trent-** [comment]
Wouldn't installing through the package manager be the better option so any updates would come through with regular system updates? From what I can see, most distro's include the package.

**Comment by martindsouza** [comment]
I agree, and that is the preferred method for most of the packages.

Right now I don't see it in the default list for CentOS. Do you know which repo we need to add to yum for it? As well also need for debian / `apt-get`.

**Comment by trent-** [comment]
Ah, at the time of my last comment I didn't get to search on CentOS. I noticed it was a part of debian and fedora so thought it must be pretty standard.

* [Debian](https://packages.debian.org/search?keywords=rlwrap&searchon=names&suite=stable&section=all)
* [Fedora](https://apps.fedoraproject.org/packages/rlwrap)

For CentOS, it's a part of the epel repo - likely need to install. See here: http://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/

```bash
# yum info rlwrap
Available Packages
Name        : rlwrap
Arch        : i686
Version     : 0.42
Release     : 1.el6
Size        : 91 k
Repo        : epel
Summary     : Wrapper for GNU readline
URL         : http://utopia.knoware.nl/~hlub/rlwrap/
License     : GPLv2+
```

**Comment by trent-** [comment]
Actually, a bit more searching and there's a package in the extras repo you can use to enable the epel repo, so you don't need to download an rpm as per the link above. See: https://www.centosblog.com/enable-epel-repo-on-centos-5-and-centos-6/.

```bash
# yum install epel-release
```

**Comment by martindsouza** [comment]
Thanks for the info. I just modified to remove the need for manual install and use `yum` and `apt-get` to install `rlwrap`.
