### ISSUE TITLE
Instance administrator password will not be set

### ISSUE THREAD

**Issue by fuzziebrain** [OraOpenSource/oraclexe-apex#34]
apxxepwd.sql is no longer available in APEX 5.0 installation package. Need to find an alternative method for setting the Instance Administrator's password.

File affected: scripts/apex.sh

**Comment by martindsouza** [comment]
Issue is due to using sql*Plus command `accept`. http://stackoverflow.com/questions/26706862/passing-parameter-to-sqlplus-script-containing-accept-from-shell-script?rq=1 provides some ideas on how to resolve.

**Comment by martindsouza** [comment]
Fixed and made backwards compatible with 4.x installations. May not support backwards compatibility for ever.
