### ISSUE TITLE
Try using << EOF to get around prompts

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/oraclexe-apex#38]
Example:

```bash
sqlplus sys/$OOS_ORACLE_PWD as sysdba @apxchpwd << EOF1
$OOS_APEX_ADMIN_USER_NAME
$OOS_APEX_ADMIN_EMAIL
$OOS_APEX_ADMIN_PWD
EOF1
```

If we can use this for the ords configuration then don't require user intervention. Only catch is Java may be an issue.

**Comment by martindsouza** [comment]
Tried and it didn't work. Will still see if they're different alternatives.

**Comment by trent-** [comment]
How about piping in those values?

I think apex 4.2 only accepts one param (the password), so I haven't fully tested this, but something like:

```bash
echo \
$OOS_APEX_ADMIN_USER_NAME \
$'\n'\
$OOS_APEX_ADMIN_EMAIL \
$'\n'\
$OOS_APEX_ADMIN_PWD\
| sqlplus sys/$OOS_ORACLE_PWD as sysdba @apxchpwd
```

What I did do was test changing the password with just one variable ($OOS_APEX_ADMIN_PWD), and it did work. And also passing in multiple variables separated by a new line with the `$'\n'` syntax in a test script - with the idea grabbed from here: http://stackoverflow.com/a/9139891/3476713.

**Comment by martindsouza** [comment]
We could use that in the https://github.com/OraOpenSource/oraclexe-apex/blob/master/scripts/apex.sh script instead of the `EOF` technique.

The real issue though is in the https://github.com/OraOpenSource/oraclexe-apex/blob/master/scripts/ords.sh script. Specifically the call to `java -jar ords.war` I can't seem to pipe in values to it (which is why there is some manual intervention required). In ORDS3 we can use a response file to handle most of the configuration however the documentation states that it will still prompt the user for the passwords: http://docs.oracle.com/cd/E56351_01/doc.30/e56293/install.htm#CHDECAFJ

Any ideas on this?

On a side note we've created a Slack account for OOS discussions. If you want to join please email or DM me your address.

**Comment by trent-** [comment]
Not sure if we'll be able to get around this. I was testing this morning with `java.io.InputStreamReader` which seems to accept pipes fine, but it seems they are using` java.io.Console` to read user input, which doesn't support input/output redirection.

> Whether a virtual machine has a console is dependent upon the underlying platform and also upon the manner in which the virtual machine is invoked. If the virtual machine is started from an interactive command line without redirecting the standard input and output streams then its console will exist and will typically be connected to the keyboard and display from which the virtual machine was launched.<sup>[1](https://docs.oracle.com/javase/7/docs/api/java/io/Console.html)</sup>

**Comment by martindsouza** [comment]
Thanks for the detailed info. I'll close this for now.
