### ISSUE TITLE
Validate OOS_ORACLE_HTTP_PORT

### ISSUE THREAD

**Issue by trent-** [OraOpenSource/oraclexe-apex#42]
config.properties has the following comment:
```bash
#Use 8081 so no conflicts with Tomcat. This is configured for plsql gateway (not used)
OOS_ORACLE_HTTP_PORT=8081
```

Assume this is in reference to potential conflict with port 8080. Perhaps this should be added to  scripts/config_validation.sh

**Comment by martindsouza** [comment]
Yes this is to deal with the Tomcat conflict. If we really want to make this more "correct" we can add in the Tomcat port in the config and ensure that these two don't conflict. I'm not sure how / where to config the Tomcat port though.
