### ISSUE TITLE
Suppress standard out in install script

### ISSUE THREAD

**Issue by trent-** [OraOpenSource/oraclexe-apex#43]
There is lots of output in installation. Would be good to suppress this and also easy to find any errors on the console.

**Comment by martindsouza** [comment]
If we do suppress it we should have a verbose mode flag to allow for all the output.

I know that @fuzziebrain was looking into this for Vagrant since the APEX install takes up most of the messaging and he wasn't able to disable that. May want to speak with him about it.

**Comment by trent-** [comment]
Thinking about this some more, I think the following might be good:

1. Have standard echo output about steps - "Installing tomcat, installing ords, etc"
* Pipe standard out to /tmp/oraclexe-install.log
* Support for -v flag, which will also display standard output in console
* Pipe errors out to /tmp/oraclexe-error.log
* Always display error output in console

**Comment by martindsouza** [comment]
I like this idea. What about storing the log files directly in the main directory (rather than /tmp). Perhaps in a `logs` folder and then update `.gitignore` to exclude any log files in `logs`?

**Comment by fuzziebrain** [comment]
Yes. I have had Vagrant fail on some machines because it was not able to create enough threads. If we are piping outputs into a log file by default, then I'll remove the action from the vagrantfile.
