### ISSUE TITLE
Set up rlwrap

### ISSUE THREAD

**Issue by trent-** [OraOpenSource/oraclexe-apex#76]
Currently rlwrap is installed but not used anywhere. Should be set up to wrap around sqlplus and rman.

```bash
alias sqlplus='rlwrap sqlplus'
alias rman='rlwrap rman'
```

**Comment by felwehedi** [comment]
It is a nice idea to have it but by default i would suggest using a different alias name than sqlplus or rman.
For more information why http://www.dba-oracle.com/t_rlwrap.htm. FYI i had an issue when building on Oracle Linux rlwrap is not installed by default on oracle linux.  I would suggest to use rlsqlplus and rlrman just in case someone is still interested in having this feature.

**Comment by tschf** [comment]
> FYI i had an issue when building on Oracle Linux rlwrap is not installed by default on oracle linux.

rlwrap isn't installed by default anywhere. That's why we install it. Is rlwrap not getting installed in Oracle Linux?

**Comment by felwehedi** [comment]
Nope it isn't getting installed so the AOP part of the installation is the only thing that didn't work but manually installing it resolved the issue. In addition to sqlplus not working due to alias but all is ok now :)

**Comment by tschf** [comment]
Oh yeah. I also note that Oracle Linux isn't in the supported distro's according to the README.

@fuzziebrain Do you have OL? Can you confirm this about `rlwrap`?

**Comment by fuzziebrain** [comment]
I have a VM running OL73. rlwrap is available from the epel that itself, isn't added by default.

**Comment by tschf** [comment]
> I have a VM running OL73. rlwrap is available from the epel that itself, isn't added by default.

Yeah.. the code adds the epel repository then install rlwrap, I thought

**Comment by fuzziebrain** [comment]
That's correct, but I think the problem is that you won't find the epel rpms in any of the default repositories. I have had to install the rpm from the EPEL website.

**Comment by tschf** [comment]
Oh.. so this isn't valid on OL?
https://github.com/OraOpenSource/OXAR/blob/c4bdc2c5776e3a24cdda2e7bbac02b72d4230ae8/scripts/packages.sh#L8

**Comment by tschf** [comment]
Looks like: https://blogs.oracle.com/wim/using-epel-repos-with-oracle-linux

Looks like we'd need, for OL:

```
# wget http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-5.noarch.rpm
# rpm -ivh epel-release-6-5.noarch.rpm
```
