### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rdupuy11** [OraOpenSource/oraclexe-apex#86]
* Installing Oracle XE *

######################################################################## 100.0%
error: %pre(oracle-xe-11.2.0-1.0.x86_64) scriptlet failed, exit status 1
error: oracle-xe-11.2.0-1.0.x86_64: install failed

What might help is if you started by advising us exactly what Amazon Machine Image to download.

Turns out I was first failing on space.  I found out many Amazon AMI's only assign 8GB of space, even if you chose 30GB in the Amazon EC2 interface.

It wasn't as simple as use resize2fs, first I found out the instance I downloaded used xfs - and the command to grow that didn't work because I first had to modify the partition table.

After getting 30GB space going - I at first tried running the scripts again, but that failed, so then I deleted it all and started from scratch.  Although at first this appeared to work, turns out Restful Service continue to do nothing.

RESTful Services->RESTful Service Module->Resource Template->Resource Handler->Test Resource 
Handler

Clicking on the TEST button does nothing, and putting them directly in the browser with a guess at the correct URL also does nothing.

OK - final edit to this message, after I reloaded Tomcat and examined the url created by the test button:
http://server:-1/ords/oos_user/hr/empinfo/

I removed the -1 as the port and pasting that directly into the browser, I now get results from the restful service. 

I do not know why there is a negative 1 in the port....but I now have a server that can potentially create a rest service - so this is nice.  Thanks for your work, it certainly helped.

**Comment by martindsouza** [comment]
Thanks for the feedback. A few comments:

re AWS: We have a AWS doc here: https://github.com/OraOpenSource/oraclexe-apex/blob/master/docs/amazon_aws.md Perhaps you can updated it with the information that you think is missing, specifically regarding the space issue and some of the configuration settings that you found helpful.

re REST bug: Though we didn't have the `-1` issue that you encountered, there was an issue when integrating with ORDS 3, which has now been fixed as issue #80. 

I recommend trying the latest build script. We fixed other minor issues and it is also a complete silent install.

**Comment by trent-** [comment]
The `-1` port bug seems resolved in the latest ORDS release.
