### ISSUE TITLE
Builder session lost after going to export repository

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/oraclexe-apex#89]
When I import and install an application, I need to re-login to builder. The application is successfully installed - follow steps to import an application, after installing, you are redirected to the builder login page (never get to the install success page (57)).

Actually, whenever I go to the export repository, and try and navigate away, I'm taken to the builder login page. 

Only happens when on Node4Ords - running through tomcat is fine.

**Comment by martindsouza** [comment]
@trent- Is this covered in the `apex_util.host_url(p_option => 'SCRIPT');` issue with ORDS 3: https://community.oracle.com/thread/3721269  If so we can probably close this ticket as it's an ORDS issue.

**Comment by trent-** [comment]
I'm not sure if they're the same issue, I tried in standalone mode on port 80 and didn't get the same result. Interestingly after running in standalone mode, and switching back to n4o, I don't get the issue any more (even after a system reboot).

**Comment by martindsouza** [comment]
Found another way to trigger this:

- Login
- SQL Workshop
- RESTful Services
  - Click the "Reset Sample Data" if oracle.example.hr is not present
- Click "oracle.example.hr"
 - Select `empinfo/GET` 
 - Test
  - This will now display the test data
- Click the back button
 - You should now be logged out (not good)

**Comment by tschf** [comment]
This was tracked in an issue on the node4ords project: https://github.com/OraOpenSource/node4ords/issues/17

Resolved on 27-JUL-2015
