### ISSUE TITLE
Add Debian support

### ISSUE THREAD

**Issue by tensau** [OraOpenSource/oraclexe-apex#9]
Would be very nice to have support for Debian-based systems

**Comment by martindsouza** [comment]
Is this something you could work on? If Debian supports ```yum``` (I think it natively uses ```apt-get```) then it would make the integration a lot easier.

**Comment by rangerzzoxz** [comment]
Will do

**Comment by fuzziebrain** [comment]
Should be fully resolved in #47.

**Comment by trent-** [comment]
As per previous comment, Debian support has been incorporated. There is a separate issue relating to the proper set up of firewall: https://github.com/OraOpenSource/oraclexe-apex/issues/96
